name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start SonarQube
        run: |
          docker run -d --name sonarqube -p 9000:9000 sonarqube:lts
          sleep 20  # Adjust as needed

      - name: Run SonarQube Scanner
        run: |
          export SONAR_HOST="http://localhost:9000"
          export SONAR_PROJECT_KEY="your_project"
          export SONAR_TOKEN="18d181f56070e48bf546a27b5470f49cbd34842d"

          sonar-scanner \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST \
            -Dsonar.login=$SONAR_TOKEN

    # Cleanup step to stop and remove the SonarQube container
  cleanup:
    if: always()  # Ensures cleanup runs even if previous steps fail
    runs-on: ubuntu-latest
    steps:
      - name: Stop and Remove SonarQube Container
        run: |
          docker stop sonarqube || true
          docker rm sonarqube || true
